language: cpp

matrix:
  include:
    - name: Test Ubuntu 16.04 + gcc-7 + codecov + (sonarcloud)
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3.7-dev
            - python3.7-venv
        sonarcloud:
          organization: "utilforever-github"
          token:
            secure: "WCmV8d5MDCtL+dqpzdRMNYL7/I6FzEAihaFtUjypMwJCLzBVkKSZYAE7XnLQiLZrlx9O5qYEnqRGEI0O1MvP2RrrSDDkz+5xCm0jAP9v2ymkMQ92brYgKQqZUHcoUuAzb+qn2nHFqTuyZ7aazzXp4ZhRYUprbRai/oANcI/RwHdqTOS0P51RkG/kPmuL54QbZ/K3ijx1L+TtID2B3BwRrd74EAGcaNkwPwtda+eK0ZJN4Y3jJ6HYvimXBFYPzRigYxrU1BkKp40444cUaL4enFwTRhim0WP1T8kaZVLqjlK1EXGcBYhNu/OiUOlrIEz8RjEUHLjvtBJArPP4NMlD5Z9NrA43E4EHYmg6b/FuFHu3ia5Dn4Ovg1SxaXB3EaRMctx5bAwO9gztiUx/DW7GGFP/xFxDoo/KbOtv4nYjEGzlr01KTSxeKVmftYC/XQ0K+tAqtPTH1WXrQ6LENRLmRyuQDERFyBpm/J5RCDkxKJpERso5EPHu+w/vjHV9E5EW+LVAC9OmbHdvRwppcNuq8jGXPjqRo3g8SaqKDng/4xUgTJrXk/f+d/Nub1Sc9ICfnPJxz9Ln5KDDi7jA2lGfC5fmHDKCHlH9Zubbx3q9L0QkGYy4N6NhRvQTXjSKXDF2mYGVNYjtBrSkKBpAeDpHazje5tODNqeDMF2ILpKJeNo="
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
      script:
        - |
          if [[ -n "${TRAVIS_PULL_REQUEST_SLUG}" && "${TRAVIS_PULL_REQUEST_SLUG}" != "${TRAVIS_REPO_SLUG}" ]]; then
            echo "The pull request from ${TRAVIS_PULL_REQUEST_SLUG} is an EXTERNAL pull request. Skip sonar analysis."
            sh Scripts/travis_build_codecov.sh
          else
            sh Scripts/travis_build_codecov_sonar.sh
          fi
    - name: Test Docker based on Ubuntu 18.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh
    - name: Test Docker based on Ubuntu 20.04 LTS + gcc
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.focal focal
    - name: Test Docker based on Ubuntu 20.04 LTS + gcc-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.focal.gcc-latest focal-gcc-latest
    - name: Test Docker based on Ubuntu 20.04 LTS + clang-latest
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh Scripts/travis_build_docker.sh Scripts/Dockerfile.focal.clang-latest focal-clang-latest
    - name: Test OS X 10.14 + Xcode 10.2 + clang
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - sh Scripts/travis_build.sh
  before_install:
    - eval "${MATRIX_EVAL}"